functionsDirectory = "/Users/neginmoradi/Documents/THERAN/netlify/functions"
functionsDirectoryOrigin = "config"
plugins = []
headers = []
redirects = []

[build]
publish = "/Users/neginmoradi/Documents/THERAN/dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "/Users/neginmoradi/Documents/THERAN/netlify/functions"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"